version: "3.9"
services:
  mysql:
    image: mysql:8-debian
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - ./.docker-storage/mysql:/var/lib/mysql
