version: "3.9"
services:
  mysql:
    image: mysql:8.0.31-debian
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.mysql
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./.docker-storage/mysql:/var/lib/mysql
